server:
  port: 8080

spring:
  security:
    logintype: JSON
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/stupiddog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    #使用druid类型
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      # 初始化大小，最小，最大


      initial-Size: 5
      min-Idle: 5
      max-Active: 20
      # 配置获取连接等待超时的时间(毫秒)
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
      filters: stat, wall, log4j
      # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
      connection-properties: ruid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000









  #thymeleaf
  thymeleaf:
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
    #后缀 ,默认是.html, 可以不用配置
    suffix: .html
    #检查模板位置是否存在
    check-template-location: true
    #编码
    encoding: utf-8
    servlet:
      content-type: text/html
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML
    #开发配置为false,避免修改模板还要重启服务器
    cache: false


mybatis:
  #映射别名路径
  type-aliases-package: com.jie.stupiddog.pojo
  #扫描mapper文件路径
  mapper-Locations: classpath:mybatis/mapper/*.xml,classpath:mybatis/mapper/console/*.xml
  configuration:
    #开启驼峰命名法
    map-underscore-to-camel-case: true

#showSql 后面的路径指的是mybatis对应的方法接口所在的包
logging:
  level:
    com.jie.stupiddog.dao: debug
